### ISSUE TITLE
Make getFlipMap() a global var

### ISSUE THREAD

**Issue by mjangda** [chrisscott/flippy#3]
Since we don't need to regenerate getFlipMap() every time we want to flip something and it won't change on-the-fly, we can just convert it into a global variable for a potential performance gain.

**Comment by chrisscott** [comment]
I'm pretty sure I had it global to begin with and then had a :beer: and decide to refactor... Thanks for the feedback!

Closed with #4.

**Comment by mjangda** [comment]
:star: :star: :star:
